Document -Xverify:none to work around VerifyError
This documents how to work around:

  java.lang.VerifyError: Expecting a stack map frame

when inserting a Java-8-compiled net.imagej:ij into Fiji
as reported here and on image.sc:

  https://github.com/imagej/ij1-patcher/issues/50

Also, documentation is added on the use of ImageJ.cfg,
replacing prior references to jvm.cfg.

Co-authored-by: Curtis Rueden <ctrueden@wisc.edu>